movies/config/routes.rb
Movies::Application.routes.draw do
  resources :characters

  resources :productions

  resources :actors

  resources :movies

end

movies/app/models/actor.rb
class Actor < ActiveRecord::Base


	has_many :productions
	has_many :movies, through: :productions
	has_many :chracters, through: :productions


  attr_accessible :age, :country, :name, :rating, :movie_id, :character_id, :actors_image, :remove_actors_image

  mount_uploader :actors_image, MovieImageUploader
end

movies/app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @actors }
    end
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
    @actor = Actor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @actor }
    end
  end

  # GET /actors/new
  # GET /actors/new.json
  def new
    @actor = Actor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @actor }
    end
  end

  # GET /actors/1/edit
  def edit
    @actor = Actor.find(params[:id])
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(params[:actor])

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render json: @actor, status: :created, location: @actor }
      else
        format.html { render action: "new" }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /actors/1
  # PUT /actors/1.json
  def update
    @actor = Actor.find(params[:id])

    respond_to do |format|
      if @actor.update_attributes(params[:actor])
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor = Actor.find(params[:id])
    @actor.destroy

    respond_to do |format|
      format.html { redirect_to actors_url }
      format.json { head :no_content }
    end
  end
end

movies/app/helpers/actors_helper.rb
module ActorsHelper
end

movies/app/views/actors/_form.html.erb
<%= form_for(@actor) do |f| %>
  <% if @actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% @actor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.file_field :actors_image %>
    <%= f.label :actors_image %>
  </div>
  <div class="field">
    <%= f.check_box :remove_actors_image %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

movies/app/views/actors/edit.html.erb
<h1>Editing actor</h1>

<%= render 'form' %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

movies/app/views/actors/index.html.erb
<h1>Listing actors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Rating</th>
  </tr>

<% @actors.each do |actor| %>
  <tr>
    <% if actor.actors_image.thumb.url %>
      <td><%= image_tag actor.actors_image.thumb.url %></td>
    <% end %>
    <td><%= link_to actor.name, actor %></td>
    <td><%= actor.rating %></td>
    <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
    <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Actor', new_actor_path %>

movies/app/views/actors/new.html.erb
<h1>New actor</h1>

<%= render 'form' %>

<%= link_to 'Back', actors_path %>

movies/app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @actor.name %>
</h1>

<% if @actor.actors_image.details.url %>
  <%= image_tag @actor.actors_image.details.url %>
<% end %>

<p>
  <b>Age:</b>
  <%= @actor.age %>
</p>

<p>
  <b>Country:</b>
  <%= @actor.country %>
</p>

<p>
  <b>Rating:</b>
  <%= @actor.rating %>
</p>

<p>
  <b>Movies:</b>
  <% @actor.movies.each do |movie| %>
  <p> <%= link_to movie.name, movie_path(movie) %></p>
    <% end %>
</p>


<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>