movies/config/routes.rb
Movies::Application.routes.draw do
  resources :characters

  resources :productions

  resources :actors

  resources :movies

end

movies/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end
end

movies/app/helpers/movies_helper.rb
module MoviesHelper
end

movies/app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.file_field :movie_image %>
    <%= f.label :movie_image %>
  </div>
  <div class="field">
    <%= f.check_box :remove_movie_image %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :float %><br />
    <%= f.text_field :float %>
  </div>
  <div class="field">
    <%= f.label :storyline %><br />
    <%= f.text_area :storyline %>
  </div>
  <div class="field">
    <%= f.label :certificate %><br />
    <%= f.text_field :certificate %>
  </div>
  <div class="field">
    <%= f.label :gross %><br />
    <%= f.text_field :gross %>
  </div>
  <div class="field">
    <%= f.label :runtime %><br />
    <%= f.text_field :runtime %>
  </div>
  <div class="field">
    <%= f.label :release_date %><br />
    <%= f.text_field :release_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

movies/app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

movies/app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Year</th>
    <th>Rating</th>
    <th>Certificate</th>
    <th>Gross</th>
  </tr>

<% @movies.each do |movie| %>
  <tr>
    <% if movie.movie_image.thumb.url %>
      <td><%= image_tag movie.movie_image.thumb.url %></td>
    <% end %>
    <td><%= link_to movie.name, movie%></td>
    <td><%= movie.year %></td>
    <td><%= movie.rating %></td>
    <td><%= movie.certificate %></td>
    <td>$<%= movie.gross %></td>
    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie', new_movie_path %>

movies/app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

movies/app/views/movies/show.html.erb
<h1>
  <%= @movie.name %>
</h1>

<% if @movie.movie_image.details.url %>
  <%= image_tag @movie.movie_image.details.url %>
<% end %>

<p>
  <b>Year:</b>
  <%= @movie.year %>
</p>

<p>
  <b>Genre:</b>
  <%= @movie.genre %>
</p>

<p>
  <b>Rating:</b>
  <%= @movie.rating %>
</p>

<p>
  <b>Float:</b>
  <%= @movie.float %>
</p>

<p>
  <b>Storyline:</b>
  <%= @movie.storyline %>
</p>

<p>
  <b>Certificate:</b>
  <%= @movie.certificate %>
</p>

<p>
  <b>Gross:</b>
  <%= @movie.gross %>
</p>

<p>
  <b>Runtime:</b>
  <%= @movie.runtime %>
</p>

<p>
  <b>Release date:</b>
  <%= @movie.release_date %>
</p>

<p>
  <b>Actors:</b>
  <% @movie.actors.each do |actor| %>
  <p> <%= link_to actor.name, actor_path(actor) %></p>
    <% end %>
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>