movies/config/routes.rb
Movies::Application.routes.draw do
  resources :characters

  resources :productions

  resources :actors

  resources :movies

end

movies/app/models/production.rb
class Production < ActiveRecord::Base

belongs_to :movie
belongs_to :actor
belongs_to :character


  attr_accessible :actor_id, :movie_id, :character_id
end

movies/app/controllers/productions_controller.rb
class ProductionsController < ApplicationController
  # GET /productions
  # GET /productions.json
  def index
    @productions = Production.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @productions }
    end
  end

  # GET /productions/1
  # GET /productions/1.json
  def show
    @production = Production.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @production }
    end
  end

  # GET /productions/new
  # GET /productions/new.json
  def new
    @production = Production.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @production }
    end
  end

  # GET /productions/1/edit
  def edit
    @production = Production.find(params[:id])
  end

  # POST /productions
  # POST /productions.json
  def create
    @production = Production.new(params[:production])

    respond_to do |format|
      if @production.save
        format.html { redirect_to @production, notice: 'Production was successfully created.' }
        format.json { render json: @production, status: :created, location: @production }
      else
        format.html { render action: "new" }
        format.json { render json: @production.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /productions/1
  # PUT /productions/1.json
  def update
    @production = Production.find(params[:id])

    respond_to do |format|
      if @production.update_attributes(params[:production])
        format.html { redirect_to @production, notice: 'Production was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @production.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productions/1
  # DELETE /productions/1.json
  def destroy
    @production = Production.find(params[:id])
    @production.destroy

    respond_to do |format|
      format.html { redirect_to productions_url }
      format.json { head :no_content }
    end
  end
end

movies/app/helpers/productions_helper.rb
module ProductionsHelper
end

movies/app/views/productions/_form.html.erb
<%= form_for(@production) do |f| %>
  <% if @production.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@production.errors.count, "error") %> prohibited this production from being saved:</h2>

      <ul>
      <% @production.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie_id %><br />
    <%= f.number_field :movie_id %>
  </div>
  <div class="field">
    <%= f.label :actor_id %><br />
    <%= f.number_field :actor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

movies/app/views/productions/edit.html.erb
<h1>Editing production</h1>

<%= render 'form' %>

<%= link_to 'Show', @production %> |
<%= link_to 'Back', productions_path %>

movies/app/views/productions/index.html.erb
<h1>Listing productions</h1>

<table>
  <tr>
    <th>Movie</th>
    <th>Actor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @productions.each do |production| %>
  <tr>
    <td><%= production.movie_id %></td>
    <td><%= production.actor_id %></td>
    <td><%= link_to 'Show', production %></td>
    <td><%= link_to 'Edit', edit_production_path(production) %></td>
    <td><%= link_to 'Destroy', production, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Production', new_production_path %>

movies/app/views/productions/new.html.erb
<h1>New production</h1>

<%= render 'form' %>

<%= link_to 'Back', productions_path %>

movies/app/views/productions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Movie:</b>
  <%= @production.movie_id %>
</p>

<p>
  <b>Actor:</b>
  <%= @production.actor_id %>
</p>


<%= link_to 'Edit', edit_production_path(@production) %> |
<%= link_to 'Back', productions_path %>